version: 1
update_configs:
    - package_manager: "java:gradle"
      directory: "./demo-java/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./demo-java/"
      update_schedule: "weekly"
      target_branch: "devsite"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./demo-kotlin/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"
